// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAoHieScljNhMX6JqY8OD1qZY7e8mgT-y4",
    authDomain: "ecommercemad-1c610.firebaseapp.com",
    projectId: "ecommercemad-1c610",
    storageBucket: "ecommercemad-1c610.appspot.com",
    messagingSenderId: "350559422755",
    appId: "1:350559422755:web:6cf98f0f160467099ce496"
  );
  


  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyBivtm1cSmtBWzocFrw-lGrZZm_HHrG55c',
  //   appId: '1:350559422755:android:55cbe4f535e91a1c9ce496',
  //   messagingSenderId: '350559422755',
  //   projectId: 'ecommercemad-1c610',
  //   storageBucket: 'ecommercemad-1c610.appspot.com',
  // );
    static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivtm1cSmtBWzocFrw-lGrZZm_HHrG55c',
    appId: '1:350559422755:android:c432f9be274c28fd9ce496',
    messagingSenderId: '350559422755',
    projectId: 'ecommercemad-1c610',
    storageBucket: 'ecommercemad-1c610.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivtm1cSmtBWzocFrw-lGrZZm_HHrG55c',
    appId: '1:350559422755:android:55cbe4f535e91a1c9ce496',
    messagingSenderId: '350559422755',
    projectId: 'ecommercemad-1c610',
    storageBucket: 'ecommercemad-1c610.appspot.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjz_xUfFzK8DlVJUnYpanDv2s8AI9KhpQ',
    appId: '1:302962007808:ios:be0965d2d44a3fc5915de5',
    messagingSenderId: '302962007808',
    projectId: 'fire-base-test-2-c65e9',
    storageBucket: 'fire-base-test-2-c65e9.appspot.com',
    iosBundleId: 'com.example.firebaseSetup.RunnerTests',
  );
}
